CREATE DATABASE ANIVERSARIO;

USE ANIVERSARIO;

CREATE TABLE CONVIDADOS(
	id_Convidado INT AUTO_INCREMENT,
	nm_Convidado VARCHAR(30),
	nr_IdadeConvidado INT,
	nr_ConsumoLiquido INT,
	nr_ConsumoSolido INT,
	PRIMARY KEY (id_Convidado)
);

CREATE TABLE ITENS(
	id_Itens INT AUTO_INCREMENT,
	nm_Item VARCHAR(30),
	PRIMARY KEY (id_Itens)
);

DELIMITER //

CREATE PROCEDURE AdicionarItem (IN Item VARCHAR(30))
BEGIN
	
	INSERT INTO ITENS VALUES (NULL, Item);

END //

DELIMITER ;

DELIMITER //

CREATE PROCEDURE AdicionarConvidado(IN NOME VARCHAR(30), IN IDADE INT, IN CONSUMOL INT, IN CONSUMOS INT)
BEGIN
	INSERT INTO CONVIDADOS VALUES (NULL, NOME, IDADE, CONSUMOL, CONSUMOS);
END //

DELIMITER ;

CREATE VIEW VerConvidados AS
SELECT nr_IdadeConvidado, nm_Convidado, nr_ConsumoLiquido, nr_ConsumoSolido FROM CONVIDADOS; 

CREATE VIEW VerItens AS
SELECT nm_Item FROM ITENS; 